---
# tasks file for roles/Lamp
# Install Apache & Httpd

- name: Install apache2 in Ubuntu
  apt:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Set Apache2 to Automatically Start in Ubuntu
  service:
    name: apache2
    enabled: yes
    state: started
  when: ansible_distribution == "Ubuntu"

- name: installation of httpd in CentOS
  dnf:
    name:
      - httpd
      - php
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS"

- name: Set httpd to Automatically start in CentOS
  service:
    name: httpd
    enabled: yes
    state: started
  when: ansible_distribution == "CentOS"

# Install MariaDB

- name: install MariaDB package in Ubuntu
  apt:
    name:
      - mariadb-server
      - mariadb-client
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Set MariaDB to Enable and start in Ubuntu
  service:
    name: mariadb
    enabled: yes
    state: started
  when: ansible_distribution == "Ubuntu"

- name: install MariaDB package in centos
  dnf:
    name:
      - mariadb-server
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS"

- name: Set MariaDB to Enable and start in CentOS
  service:
    name: mariadb
    enabled: yes
    state: started
  when: ansible_distribution == "CentOS"

# Install PHP

- name: Installation of PHP in Ubuntu
  apt:
    name:
      - software-properties-common
      - php
      - php-curl
      - php-gd
      - php-mbstring
      - php-xml
      - php-xmlrpc
      - php-soap
      - php-intl
      - php-zip
      - php-cli
      - php-mysql
      - php-gmp
      - php-imagick
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: installation of PHP in CentOS
  dnf:
    name:
      - php
      - php-curl
      - php-gd
      - php-mbstring 
      - php-xml
      - php-xmlrpc
      - php-soap
      - php-intl
      - php-zip
      - php-cli
      - php-gmp
    state: latest
    update_cache: yes
  when: ansible_distribution == "CentOS"
